### PR TITLE
FACES-2696 Utilize Portlet 3.0 dynamic resource dependency feature (add TCK test)

### PR DESCRIPTION
**Pull request by stiemannkj1**
~~@ngriffin7a, please backport this commit to `4.x` **only**.~~

### CODE REVIEW

**Comment by ngriffin7a** [comment]
Merged. Thank you.

**Comment by stiemannkj1** [comment]
@ngriffin7a, updated, please merge to `master` **only**. ~~The backport to `4.x` has been done here: https://github.com/liferay/liferay-faces-portal/pull/112~~

**Comment by stiemannkj1** [comment]
@ngriffin7a, updated. The backport to `4.x` has been done here: https://github.com/liferay/liferay-faces-portal/pull/113

**Comment by ngriffin7a** [comment]
Merged and backported to 4.x. Thank you.

**Comment by ngriffin7a** [comment]
Reverted backport to 4.x because of the existence of #113

**Pull request merged**
