### PR TITLE
Workaround broken method c.l.p.k.util.HtmlUtil#extractText

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The interface HtmlUtil was incompatibly changed in the liferay commit:

https://github.com/liferay/liferay-portal/commit/0f098e0a87460a8a1b7afb13c7fbc6af25bf4f0b

The extractText method was moved to a new interface, breaking all
current users. This commit checks which of the two variants is present
and invokes that one using a MethodHandle.

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
This is the thrown exception:

```
java.lang.NoSuchMethodError: 'java.lang.String com.liferay.portal.kernel.util.HtmlUtil.extractText(java.lang.String)'
        at com.liferay.faces.portal.component.inputrichtext.internal.PlainTextCharUtil.getHTMLPlainTextCharCount(PlainTextCharUtil.java:59) ~[com.liferay.faces.portal-4.1.0.jar:4.1.0 (Oct 26, 2020 AD)]
        at com.liferay.faces.portal.component.inputrichtext.InputRichText.validateValue(InputRichText.java:95) ~[com.liferay.faces.portal-4.1.0.jar:4.1.0 (Oct 26, 2020 AD)]
        at javax.faces.component.UIInput.validate(UIInput.java:988) ~[javax.faces-2.2.20.jar:2.2.20]
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1270) ~[javax.faces-2.2.20.jar:2.2.20]
```

**Comment by matthiasblaesing** [comment]
@ngriffin7a could you please have a look at this?

**Comment by ngriffin7a** [comment]
@matthiasblaesing Thanks so much for the pull request and for your patience. We're getting the JSR 378 API/Spec ready for approval with the JCP at this time but will make sure that we get this issue you reported gets fixed before we release the next version of liferay-faces-portal, hopefully in the next month or so.

**Comment by ngriffin7a** [comment]
@matthiasblaesing I created [FACES-3673](https://issues.liferay.com/browse/FACES-3673) in order to track this issue to closure. Please click on the "Contribute Solution" button, accept the contributor agreement, and reference this pull request URL. I'll merge your commit as soon as I am able. Thank you, Neil

**Comment by ngriffin7a** [comment]
Merged, thank you so much @matthiasblaesing ! :-)

**Comment by matthiasblaesing** [comment]
@ngriffin7a thanks for taking care!

**Pull request closed without merging**
