### PR TITLE
FACES-3133 Author selenium automation test for JSF Registration Portlet

### PR DESCRIPTION
**Pull request by stiemannkj1**
@ngriffin7a, please backport this all the way to `3.x`. I've sent a PR for the `2.x` branch.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
bp to 4.x and 3.x <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
@stiemannkj1 Please see code review commit and send a follow-up PR if there are any improvements that can be made: https://github.com/liferay/liferay-faces-portal/commit/dec0c1cdd44484dfe4b1682c7775df514cd00814

**Comment by stiemannkj1** [comment]
@ngriffin7a, looks great, I don't see any improvements to make! Thanks!

**Comment by ngriffin7a** [comment]
@stiemannkj1 One more small commit on top of my code review commit: https://github.com/liferay/liferay-faces-portal/commit/567ef080bb9e84788f0c7b88e5ceae344a1e91c6

**Pull request merged**
